# Main background
theme[main_bg]="#1e1e2e"

# Main text color
theme[main_fg]="#cdd6f4"

# Title color for boxes
theme[title]="#cdd6f4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#f5e0dc"

# Background color for selected items
theme[selected_bg]="#313244"

# Value color for selected items
theme[selected_fg]="#cba6f7"

# Color of inactive/disabled text
theme[inactive_fg]"#6c7086"

# Color of text appearing down columns
theme[graph_text]="#a6adc8"

# Misc colors for meters etc.
theme[proc_misc]="#f5c2e7"

# CPU box outline color
theme[cpu_box]="#fab387"

# Memory/Process box outline color
theme[mem_box]="#a6e3a1"

# Net box outline color
theme[net_box]="#89b4fa"

# Process box outline color
theme[proc_box]="#cba6f7"

# Directives for gradient generation
theme[div_line]="#313244"

# Temperature graph colors
theme[temp_start]="#89b4fa"
theme[temp_mid]="#fab387"
theme[temp_end]="#f38ba8"

# CPU graph colors
theme[cpu_start]="#89b4fa"
theme[cpu_mid]="#cba6f7"
theme[cpu_end]="#f38ba8"

# Mem/Disk free meter
theme[free_start]="#a6e3a1"
theme[free_mid]="#94e2d5"
theme[free_end]="#89dceb"

# Mem/Disk cached meter
theme[cached_start]="#89dceb"
theme[cached_mid]="#74c7ec"
theme[cached_end]="#89b4fa"

# Mem/Disk used meter
theme[used_start]="#fab387"
theme[used_mid]="#eba0ac"
theme[used_end]="#f38ba8"

# Download graph colors
theme[download_start]="#a6e3a1"
theme[download_mid]="#94e2d5"
theme[download_end]="#89dceb"

# Upload graph colors
theme[upload_start]="#fab387"
theme[upload_mid]="#eba0ac"
theme[upload_end]="#f38ba8"
